# Generated by Django 5.1.2 on 2024-12-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataspy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
